version: '3.9'

services:
  investigation-service:
    build:
      context: .
      dockerfile: Investigation.API/Dockerfile
    container_name: investigation-service
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    restart: unless-stopped